backend/company/urls.py
from django.urls import path
from company.views import company_view, company_create, company_join

urlpatterns = [
    path('', company_view, name='company-view'),
    path('create/', company_create, name='company-create'),
    path('join/', company_join, name='company-join'),
]

backend/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.routers import DefaultRouter
from project import api as project_api
from company import api as company_api

router = DefaultRouter()
router.register('project/projects', project_api.ProjectViewSet, 'projects')
router.register('project/tasks', project_api.TaskViewSet, 'tasks')
router.register('company/companies', company_api.CompanyViewSet, 'companies')
router.register('company/teams', company_api.TeamViewSet, 'teams')
router.register('company/positions', company_api.PositionViewSet, 'positions')
router.register('company/joinrequests',
                company_api.JoinRequestViewSet, 'joinrequests')
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing.urls')),
    path('user/', include('user.urls')),
    path('api/v1/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls')),
    path('company/', include('company.urls')),
    path('projects/', include('project.urls'))
]

if settings.DEBUG == True:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

backend/company/models.py
from django.db import models

# Create your models here.


class Company(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=500)
    city = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    phone = models.CharField(max_length=20)
    email = models.EmailField(max_length=100)
    website = models.URLField()
    logo = models.ImageField(upload_to='company_logo/',
                             blank=True, null=True, default='default.jpg')
    admin = models.ForeignKey("user.User", on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = "Companies"

    def __str__(self):
        return self.name


class Team(models.Model):
    name = models.CharField(max_length=100)
    members = models.ManyToManyField('user.Profile', blank=True)
    company = models.ForeignKey('company.Company', on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Position(models.Model):
    name = models.CharField(max_length=100)
    company = models.ForeignKey('company.Company', on_delete=models.CASCADE)
    description = models.TextField(max_length=500)

    def __str__(self):
        return self.name


class JoinRequest(models.Model):
    user = models.ForeignKey('user.User', on_delete=models.CASCADE)
    company = models.ForeignKey('company.Company', on_delete=models.CASCADE)
    description = models.TextField(max_length=500, null=True, blank=True)
    position = models.ForeignKey(
        'company.Position', on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return f'{self.company.name}-{self.user.user_name}'

backend/company/forms.py
from django import forms
from django.contrib.auth import get_user_model
from company.models import Company


User = get_user_model()


class CompanyCreationForm(forms.ModelForm):
    """
    Form for creating a new company
    """
    name = forms.CharField(label='Company Name', max_length=100)
    description = forms.CharField(label='Company Description', max_length=100)
    email = forms.EmailField(label='Company Email', max_length=100)
    phone = forms.CharField(label='Company Phone', max_length=100)
    address = forms.CharField(label='Company Address', max_length=100)
    city = forms.CharField(label='Company City', max_length=100)
    website = forms.URLField(label='Company Website', max_length=100)
    logo = forms.ImageField(label='Company Logo',
                            max_length=100, required=False)

    class Meta:
        model = Company
        fields = ("name", "description", "city", "address",
                  "phone", "email", "website", "logo",)

backend/company/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from company.forms import CompanyCreationForm
from company.models import Company, JoinRequest


@login_required
def company_view(request):
    if request.user.profile.company:
        return redirect('project_index')
    context = {
        'company_creation_form': CompanyCreationForm(),
    }
    return render(request, 'company/company.html', context)


def company_create(request):
    if request.method == 'POST':
        form = CompanyCreationForm(request.POST)
        if form.is_valid():
            print('valid')
            instance = form.save(commit=False)
            instance.admin = request.user
            instance.save()
        else:
            print(form.errors)
    return redirect('company-view')


def company_join(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        desc = request.POST.get('description')
        JoinRequest.objects.create(
            company=Company.objects.get(name=name), description=desc, user=request.user)
    return redirect('company-view')

backend/company/templates/company/company.html
{% extends "landing/base.html" %}
{% load static %}
{% block title %}projtor - Join or Create a company{% endblock %}
{% block body %}
{% load crispy_forms_tags %}
{% load tailwind_filters %}
<div class="min-h-screen">
    <section class="flex justify-center ">
        <div class="mt-10 pb-8 flex flex-col justify-center bg-gray-100 px-4 rounded-sm w-11/12 md:w-1/2">
            {% csrf_token %}
            <h1 class="my-5 text-xl font-semibold text-gray-800 text-center">Create or join an organization</h1>
            <button id="create-from-hidden-btn"
                class="py-1 my-2 mx-20 text-white bg-gray-400 ring-4 font-bold ring-gray-300 rounded-sm">Create</button>
            <form id="create_from_btn" action="{% url 'company-create' %}" method="post" class="mt-4 hidden">
                {% csrf_token %}
                {{ company_creation_form|crispy }}
                <button type="submit"
                    class="bg-purple-700 hover:bg-purple-600 text-white font-bold py-2 px-8 my-2 mx-auto rounded">Create
                    Organization</button>
            </form>
            <button id="join-from-hidden-btn"
                class="py-1 my-2 mx-20 text-white bg-green-400 ring-4 font-bold ring-green-300 rounded-sm">Join</button>
            <form id="join_from_btn" action="{% url 'company-join' %}" method="post" class="mt-4 hidden">
                {% csrf_token %}
                <label for="id_name" class="block text-gray-700 text-sm font-bold mb-2">
                    Company Name<span class="asteriskField">*</span>
                </label>
                <input type="text" name="name" maxlength="100"
                    class="textinput block px-4 text-gray-700 w-full border-gray-300 border focus:outline-none appearance-none bg-white leading-normal py-2 rounded-lg"
                    required id="id_name">
                <label for="id_name" class="block text-gray-700 text-sm font-bold mb-2">
                    Description
                </label>
                <input type="text" name="description" maxlength="100"
                    class="textinput block px-4 text-gray-700 w-full border-gray-300 border focus:outline-none appearance-none bg-white leading-normal py-2 rounded-lg"
                    id="id_description">
                <button type="submit"
                    class="bg-purple-700 hover:bg-purple-600 text-white font-bold py-2 px-8 my-2 mx-auto rounded">Send a
                    Request</button>
            </form>
        </div>
    </section>
</div>
{% endblock %}

{% block javascript %}
<script>
    var create_from_hidden_btn = document.getElementById("create-from-hidden-btn");
    var join_from_hidden_btn = document.getElementById("join-from-hidden-btn");

    var create_from = document.getElementById("create_from_btn");
    var join_from = document.getElementById("join_from_btn");
    create_from_hidden_btn.addEventListener("click", function () {
        create_from.classList.toggle("hidden");
    });
    join_from_hidden_btn.addEventListener("click", function () {
        join_from.classList.toggle("hidden");
    });
</script>
{% endblock %}